Do not silently ignore any errors that might have occurred
We encountered an issue where the database was unavailable while running
the Terraform Zitadel provider with a `project_role` resource.

After some debugging we found that Zitadel itself returned an error
(FATAL: the database system is shutting down (SQLSTATE 57P03)), but the
Zitadel provider ignored this error and removed the project role from
the state.

This, of course, caused issues when we tried to execute `terraform
apply` again when the database was restarted. As now the Zitadel
provider thought the roles didn't exist yet and tried to create them
resulting in like:

```
Error: failed to create project role: rpc error: code = AlreadyExists
desc = Role already exists (V3-DKcYh)
```

By returning any received errors this problem should no longer occur.

Note that resetting/clearning the ID is still done at the end of this
function, unless there is exactly 1 result. So functionally that didn't
change.